FROM ubuntu:22.04
LABEL maintainer="Vlad Lunculescu"
WORKDIR /app

ENV "PORT=8080"

RUN apt-get update && apt-get install -y \
    # ESUAT: python3 (Lipseste din repozitoriu)
    # ESUAT: aaa (Lipseste din repozitoriu)
    curl \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]

